CREATE TABLE minions (
id INT(11) PRIMARY KEY AUTO_INCREMENT NOT NULL,
NAME VARCHAR(50), age INT(11), town_id INT(11)
);
CREATE TABLE towns (
id INT(11) PRIMARY KEY AUTO_INCREMENT NOT NULL,
NAME VARCHAR(50)
)